# Copyright 2025 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

includes:
  quality: https://raw.githubusercontent.com/Terradue/taskfile-utils/refs/heads/main/quality.yaml

vars:
  IMAGE_NAME: ghcr.io/transpiler-mate/cwl2ogc/playground:latest

tasks:

  build-playground-dev:
    internal: true
    desc: Build the playground container
    cmds:
    - |
      docker build -t playground -f playground/Dockerfile .

  run-playground:
    desc: Run the playground container
    cmds:
    - |
      docker pull {{.IMAGE_NAME}}
      docker run --rm -it -p 80:8501 {{.IMAGE_NAME}}

  run-playground-dev:
    desc: Build and run the playground container
    cmds:
    - task: build-playground-dev
    - |
      docker run --rm -it -p 80:8501 playground

  playground: 
    desc: Run the local playground app
    cmds:
    - |
      pip install streamlit streamlit_code_editor cwltool
      cd playground
      streamlit run playground.py

  default:
    cmds:
    - task: quality:pre-commit:run
